In [2]:
a = [1,2,3]
a[:-1]

[1, 2]

In [3]:
a[-1:]

[3]

In [4]:
import numpy as np
a = np.ones((3,1))
print(a)
print(a[:-1])

b = a



[[1.]
 [1.]
 [1.]]
[[1.]
 [1.]]


In [5]:
b[0,0] = 2

In [6]:
a

array([[2.],
       [1.],
       [1.]])

In [7]:
b = b - 1

In [8]:
c = a

In [9]:
c -= 2

In [10]:
c

array([[ 0.],
       [-1.],
       [-1.]])

In [11]:
a

array([[ 0.],
       [-1.],
       [-1.]])

In [12]:
u = np.array([1,2,3])
v = np.expand_dims(u, axis=1)
w = np.expand_dims(u, axis=0)
print(v)
print(w)

[[1]
 [2]
 [3]]
[[1 2 3]]


In [13]:
x = np.array([1,0,2])
y = -1
a = 2
np.where(y*a>1, 0, y * x)
np.where(1*a>1, 0, y * x)

np.where(x > 0, 1, x)

array([1, 0, 1])