In [1]:
import numpy as np


def perceptron_through_origin(data, labels, T=100, hook=None):
    # if T not in params, default to 100
    n_mistakes = 0

    d, n = data.shape
    th = np.zeros((d, 1))
    for t in range(T):
        made_mistake = False
        for i in range(n):
            x = data[:, i:i + 1]
            y = labels[:, i:i + 1]
            if y * (th.T @ x) <= 0:
                th += y * x
                made_mistake = True
                n_mistakes += 1
        if not made_mistake:
            print("perfect th found!!")
            print(f"mistakes made: {n_mistakes}")
            return th
    print("perfect th not found :(")
    print(f"mistakes made: {n_mistakes}")
    return th


In [2]:
data = np.array([[200, 0.2, 1], [800, 0.2, 1], [200, 0.8, 1], [800, 0.8, 1]]).T
# data = np.array([[2, 0.2, 1], [8, 0.2, 1], [2, 0.8, 1], [8, 0.8, 1]]).T

labels = np.array([[-1, -1, 1, 1]])
perceptron_through_origin(data, labels, T=1000000)

perfect th found!!
mistakes made: 666696


array([[-2.000000e+02],
       [ 2.000068e+05],
       [-4.000000e+00]])

In [3]:
data = np.array([[0.2, 0.2, 1], [0.8, 0.2, 1], [0.2, 0.8, 1], [0.8, 0.8, 1]]).T

labels = np.array([[-1, -1, 1, 1]])
perceptron_through_origin(data, labels, T=1000000)

perfect th found!!
mistakes made: 7


array([[-0.2],
       [ 1.6],
       [-1. ]])

In [5]:
from code_for_hw3_part1 import make_polynomial_feature_fun
from itertools import combinations_with_replacement

make_polynomial_feature_fun(2)

for n in [1, 10, 20, 30, 40, 50]:
    num_features = sum(len(list(combinations_with_replacement("AB", i))) for i in range(0, n + 1))
    print(f"number of monomials in a {n}-degree polynomial basis: {num_features}")

Importing code_for_hw03
Imported tidy_plot, plot_separator, plot_data, plot_nonlin_sep, cv, rv, y, positive, score
Datasets: super_simple_separable_through_origin(), super_simple_separable(), xor(), xor_more()
Tests for part 2: test_linear_classifier_with_features, mul, make_polynomial_feature_fun, 
                  test_with_features
Also loaded: perceptron, one_hot_internal, test_one_hot
number of monomials in a 1-degree polynomial basis: 3
number of monomials in a 10-degree polynomial basis: 66
number of monomials in a 20-degree polynomial basis: 231
number of monomials in a 30-degree polynomial basis: 496
number of monomials in a 40-degree polynomial basis: 861
number of monomials in a 50-degree polynomial basis: 1326


In [16]:
import code_for_hw3_part2 as hw3

# Returns a list of dictionaries.  Keys are the column names, including mpg.
auto_data_all = hw3.load_auto_data('auto-mpg.tsv')

# The choice of feature processing for each feature, mpg is always raw and
# does not need to be specified.  Other choices are hw3.standard and hw3.one_hot.
# 'name' is not numeric and would need a different encoding.
features_1 = [('cylinders', hw3.raw),
              ('displacement', hw3.raw),
              ('horsepower', hw3.raw),
              ('weight', hw3.raw),
              ('acceleration', hw3.raw),
              ## Drop model_year by default
              ## ('model_year', hw3.raw),
              ('origin', hw3.raw)]
features_2 = [('cylinders', hw3.one_hot),
              ('displacement', hw3.standard),
              ('horsepower', hw3.standard),
              ('weight', hw3.standard),
              ('acceleration', hw3.standard),
              ## Drop model_year by default
              ## ('model_year', hw3.raw),
              ('origin', hw3.one_hot)]
features_3 = [('cylinders', hw3.one_hot),
              ('weight', hw3.standard),
              ]

features_list = [features_1, features_2, features_3]

# Construct the standard data and label arrays

for T in [1, 10, 50]:
    for i in range(len(features_list)):
        auto_data, auto_labels = hw3.auto_data_and_labels(auto_data_all, features_list[i])
        result = []
        for alg in [hw3.perceptron, hw3.averaged_perceptron]:
            result.append(hw3.xval_learning_alg(alg, auto_data, auto_labels, 10, T))
        print(f"T={T}, feature set {i + 1}: {result}")


avg and std {}
entries in one_hot field {}
T=1, feature set 1: [np.float64(0.6526282051282052), np.float64(0.8441025641025641)]
avg and std {'displacement': (388.3482142857143, 302.0458123396404), 'horsepower': (509.3545918367347, 333.65211517163635), 'weight': (2977.5841836734694, 848.3184465698363), 'acceleration': (15.541326530612244, 2.7553429127509967)}
entries in one_hot field {'cylinders': [3.0, 4.0, 5.0, 6.0, 8.0], 'origin': [1.0, 2.0, 3.0]}
T=1, feature set 2: [np.float64(0.7908333333333333), np.float64(0.9004487179487182)]
avg and std {'weight': (2977.5841836734694, 848.3184465698363)}
entries in one_hot field {'cylinders': [3.0, 4.0, 5.0, 6.0, 8.0]}
T=1, feature set 3: [np.float64(0.6686538461538463), np.float64(0.8953205128205128)]
avg and std {}
entries in one_hot field {}
T=10, feature set 1: [np.float64(0.7423076923076924), np.float64(0.8366025641025641)]
avg and std {'displacement': (388.3482142857143, 302.0458123396404), 'horsepower': (509.3545918367347, 333.6521151716

In [15]:
auto_data, auto_labels = hw3.auto_data_and_labels(auto_data_all, features_2)
hw3.averaged_perceptron(auto_data, auto_labels, {"T": 1})

avg and std {'displacement': (388.3482142857143, 302.0458123396404), 'horsepower': (509.3545918367347, 333.65211517163635), 'weight': (2977.5841836734694, 848.3184465698363), 'acceleration': (15.541326530612244, 2.7553429127509967)}
entries in one_hot field {'cylinders': [3.0, 4.0, 5.0, 6.0, 8.0], 'origin': [1.0, 2.0, 3.0]}


(array([[-0.25510204],
        [ 0.98469388],
        [ 0.        ],
        [ 0.4744898 ],
        [-0.52040816],
        [ 0.0977406 ],
        [-0.89763413],
        [-1.84711922],
        [ 0.06270238],
        [-0.04591837],
        [ 0.98469388],
        [-0.25510204]]),
 array([[0.68367347]]))

In [17]:
#-------------------------------------------------------------------------------
# Review Data
#-------------------------------------------------------------------------------

# Returns lists of dictionaries.  Keys are the column names, 'sentiment' and 'text'.
# The train data has 10,000 examples
review_data = hw3.load_review_data('reviews.tsv')

# Lists texts of reviews and list of labels (1 or -1)
review_texts, review_label_list = zip(*((sample['text'], sample['sentiment']) for sample in review_data))

# The dictionary of all the words for "bag of words"
dictionary = hw3.bag_of_words(review_texts)

# The standard data arrays for the bag of words
review_bow_data = hw3.extract_bow_feature_vectors(review_texts, dictionary)
review_labels = hw3.rv(review_label_list)
print('review_bow_data and labels shape', review_bow_data.shape, review_labels.shape)

#-------------------------------------------------------------------------------
# Analyze review data
#-------------------------------------------------------------------------------

# Your code here to process the review data
accuracies = []
for T in [1, 10, 50]:
    for alg in (hw3.perceptron, hw3.averaged_perceptron):
        accuracy = hw3.xval_learning_alg(alg, review_bow_data, review_labels, 10, T)
        print(accuracy)
        accuracies.append((T, alg.__name__, accuracy))
print(accuracies)


review_bow_data and labels shape (19945, 10000) (1, 10000)


KeyboardInterrupt: 

In [18]:
th, th0 = hw3.averaged_perceptron(review_bow_data, review_labels, {"T": 10})
print(th)

[[ 0.15984]
 [-2.74048]
 [-1.23668]
 ...
 [ 0.     ]
 [-1.2001 ]
 [ 0.     ]]


In [29]:
top_indices = np.argsort(np.hstack(th))[::-1][:10]
worst_indices = np.argsort(np.hstack(th))[:10]
index_to_word = hw3.reverse_dict(dictionary)
print([index_to_word[i] for i in top_indices])
print([index_to_word[i] for i in worst_indices])


['excellent', 'delicious', 'satisfied', 'easily', 'perfect', 'skeptical', 'yummy', 'bright', 'individually', 'great']
['worst', 'awful', 'unfortunately', 'horrible', 'stuck', 'changed', 'disappointment', 'bland', 'poor', 'formula']


In [33]:
scaled_magins = (th.T @ review_bow_data + th0)
best_index = np.argmax(scaled_magins)
worst_indices = np.argmin(scaled_magins)
print(review_texts[best_index])


My boyfriend and I received the Keurig Elite brewer as a Christmas gift after lusting after the brewers all of my friends and family owned.  We have been using a trusty Cuisinart 10-cup drip brewer for a couple of years now, and while it has served us well, it was a challenge to get a consistent cup of coffee.  Somehow we always ended up on either the too-strong or two-weak side of the line, despite our best efforts to be consistent.<br /><br />I should mention that we are students living on a very strict budget and we knew that the Keurig would end up being a little bit more costly than our Cuisinart.  But we really liked the idea of brewing coffee a cup at a time and cutting down on waste.  Thankfully, my generous sister surprised us with one for Christmas and it has really turned out to be a perfect gift!<br /><br />WARNING!<br /><br />I feel it is important to mention that we almost sent this back.  Considering how I've been singing its praises, I'm sure this is surprising, but the

In [34]:
print(review_texts[worst_indices])


Fuzzy Wuzzy's Summary:<br />*** Somewhat recommended, with reservations and only lukewarm fuzzies.<br /><br />Positives:<br /><br />+ Not too expensive compared to other bottled water, although it is not cheap either.<br /><br />Negatives:<br /><br />- This bottled water product's labeling, product descriptions, and health claims are misleading.<br /><br />At first glance, this 1.5-liter bottle of water that I am reviewing looks like another one of the many varieties of bottled water on the market.  There are many kinds of bottled water: "spring water" produced from an underground formation where the groundwater naturally flows up to the Earth's surface, "artesian water" obtained from a well that taps into an underground aquifer, "mineral water" produced from a well or spring that naturally contains trace amounts of minerals that some people consider to provide health benefits, "ground/well water" produced from a well that tapes into an aquifer, "sparkling water" from a spring or well 

In [55]:

def raw_mnist_features(x):
    """
    @param x (n_samples,m,n) array with values in (0,1)
    @return (m*n,n_samples) reshaped array where each entry is preserved
    """
    raise Exception("implement me!")

def row_average_features(x):
    """
    This should either use or modify your code from the tutor questions.

    @param x (n_samples,m,n) array with values in (0,1)
    @return (m,n_samples) array where each entry is the average of a row
    """
    return np.mean(x, axis=2).T


def col_average_features(x):
    """
    This should either use or modify your code from the tutor questions.

    @param x (n_samples,m,n) array with values in (0,1)
    @return (n,n_samples) array where each entry is the average of a column
    """
    return np.mean(x, axis=1).T


def top_bottom_features(x):
    """
    This should either use or modify your code from the tutor questions.

    @param x (n_samples,m,n) array with values in (0,1)
    @return (2,n_samples) array where the first entry of each column is the average of the
    top half of the image = rows 0 to floor(m/2) [exclusive]
    and the second entry is the average of the bottom half of the image
    = rows floor(m/2) [inclusive] to m
    """
    mid = x.shape[0] //2
    top_means = np.mean(x[:, :mid, :], axis=(1, 2))
    bottom_means = np.mean(x[:, mid:, :], axis=(1, 2))
    return np.vstack(([top_means], [bottom_means]))

a = np.random.randint(low=0, high=10, size=(3, 2, 4), )
print(a)
print(np.array([np.hstack(m) for m in a]).T)
n_samples, m, n = a.shape
print(np.reshape(a, (n_samples, m*n)).T)
a_row_mean = np.mean(a, axis=2).T
a_col_mean = np.mean(a, axis=1).T
print(a_row_mean)
print(row_average_features(a))
print(a_col_mean)
print(col_average_features(a))
print(np.vstack([[np.mean(a[:,:1,:], axis=(1,2))], [np.mean(a[:,1:,:], axis=(1,2))]]))
print(top_bottom_features(a))


[[[8 1 9 3]
  [2 5 7 5]]

 [[2 6 1 4]
  [9 7 9 8]]

 [[7 3 7 7]
  [4 8 8 1]]]
[[8 2 7]
 [1 6 3]
 [9 1 7]
 [3 4 7]
 [2 9 4]
 [5 7 8]
 [7 9 8]
 [5 8 1]]
[[8 2 7]
 [1 6 3]
 [9 1 7]
 [3 4 7]
 [2 9 4]
 [5 7 8]
 [7 9 8]
 [5 8 1]]
[[5.25 3.25 6.  ]
 [4.75 8.25 5.25]]
[[5.25 3.25 6.  ]
 [4.75 8.25 5.25]]
[[5.  5.5 5.5]
 [3.  6.5 5.5]
 [8.  5.  7.5]
 [4.  6.  4. ]]
[[5.  5.5 5.5]
 [3.  6.5 5.5]
 [8.  5.  7.5]
 [4.  6.  4. ]]
[[5.25 3.25 6.  ]
 [4.75 8.25 5.25]]
[[5.25 3.25 6.  ]
 [4.75 8.25 5.25]]
