# MIT 6.036 Spring 2019: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.


In [3]:
import numpy as np

def SM(z):
  # implement softmax
  return np.exp(z)/sum(np.exp(z))

 **Problem 2A**

In [4]:
z = np.array([[-1, 0, 1]]).T
# your code here
SM(z)

array([[0.09003057],
       [0.24472847],
       [0.66524096]])

**Problem 2.C-F**

In [16]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T
# your code here
z = w.T@x
a = SM(z)
d_loss_w = x @ (a - y).T
print(a)
print(d_loss_w)

# E
w_new = w - 0.5 * d_loss_w
print(np.round(w_new, 3))

# F
z_new = w_new.T@x
a_new = SM(z_new)
print(np.round(a_new[1], 3))

[[0.24472847]
 [0.66524096]
 [0.09003057]]
[[ 0.24472847 -0.33475904  0.09003057]
 [ 0.24472847 -0.33475904  0.09003057]]
[[ 0.878 -0.833 -2.045]
 [-1.122  2.167  0.955]]
[0.772]


**Problem 3**

In [18]:
# layer 1 weights
w_1 = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
w_1_bias = np.array([[-1, -1, -1, -1]]).T
# layer 2 weights
w_2 = np.array([[1, -1], [1, -1], [1, -1], [1, -1]])
w_2_bias = np.array([[0, 2]]).T

# your code here
def ReLU(z):
    return np.where(z > 0, z, 0)
x = np.array([[3,14]]).T
z1 = w_1.T @ x +w_1_bias
a1 = ReLU(z1)
print(a1)

z2 = w_2.T @ a1 + w_2_bias
a2 = SM(z2)
print(a2)

[[ 2]
 [13]
 [ 0]
 [ 0]]
[[1.00000000e+00]
 [6.91440011e-13]]


In [ ]:
import numpy as np

T  = np.matrix([[0.0 , 0.1 , 0.9 , 0.0],
[0.9 , 0.1 , 0.0 , 0.0],
[0.0 , 0.0 , 0.1 , 0.9],
[0.9 , 0.0 , 0.0 , 0.1]])
g = 0.9
r = np.matrix([0, 1., 0., 2.]).reshape(4, 1)

print(np.linalg.solve(np.eye(4) - g * T, r))

[[6.05288295]
 [6.48663207]
 [6.7519581 ]
 [7.58553317]]
